{
 "title": "Dedicated Atlas Clusters - Hardware Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(mongodb_up, job)" } },
   {
    "name": "group_id",
    "label": "Group Id",
    "query": {
     "query": "label_values(mongodb_up{job=\"$job\"}, group_id)"
    }
   },
   {
    "name": "cl_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(mongodb_up{group_id='$group_id'}, cl_name)"
    }
   },
   {
    "name": "rs_nm",
    "label": "Replica set name",
    "query": {
     "query": "label_values(mongodb_up{group_id='$group_id', cl_name='$cl_name'}, rs_nm)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(mongodb_up{group_id='$group_id', cl_name='$cl_name',rs_nm='$rs_nm'},instance)"
    }
   },
   {
    "name": "process_port",
    "label": "Process Port",
    "query": {
     "query": "label_values(mongodb_up{group_id='$group_id', cl_name='$cl_name',rs_nm='$rs_nm'},process_port)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,30m,1h,1d" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Group Metadata",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace( sum(mongodb_up{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by ( group_id, org_id, rs_nm, cl_name), \"hostname\", \"$1\", \"instance\", \"(.*)\")\n"
    }
   ]
  },
  {
   "title": "Cluster host list",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace( sum(mongodb_info{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance, replica_state_name, process_port, rs_nm, process_type), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")"
    }
   ]
  },
  { "title": "System Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System Memory - Shared",
   "type": "graph",
   "description": "The number of kilobytes of used shared memory (shared between several processes, thus including RAM disks, SYS-V-IPC and BSD like SHMEM)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(hardware_system_memory_shared_mem_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System Memory - Buffers",
   "type": "graph",
   "description": "The number of kilobytes of buffer cache, relatively temporary storage for raw disk blocks",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(hardware_system_memory_buffers_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System Memory - Cached",
   "type": "graph",
   "description": "The number of kilobytes in the page cache.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace (sum(hardware_system_memory_cached_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System Memory - Used",
   "type": "graph",
   "description": "The number of kilobytes of physical memory in use\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(hardware_system_memory_mem_total_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) - sum(hardware_system_memory_mem_free_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System Memory - Swap",
   "type": "graph",
   "description": "The total amount of swap space in free and used, measured in kilobytes\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(hardware_system_memory_swap_total_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) - sum(hardware_system_memory_swap_free_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "swap used for host - {{hostname}}"
    },
    {
     "expr": "label_replace (sum(hardware_system_memory_swap_free_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "swap free for host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System Memory - Available",
   "type": "graph",
   "description": "An estimate of the number of kilobytes of system memory available for running new applications, without swapping",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(hardware_system_memory_mem_available_kilobytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  { "title": "System CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "System cpu - steal",
   "type": "graph",
   "description": "The percentage of time the CPU had something runnable, but the hypervisor chose to run something else. For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_steal_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / 10) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System cpu - guest",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing guest, which is included in user. For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_guest_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / 10) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System cpu - softirq",
   "type": "graph",
   "description": "The percentage of time the CPU spent performing software interrupts. For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_soft_irq_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / 10) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System cpu - irq",
   "type": "graph",
   "description": "The percentage of time the CPU spent performing hardware interrupts. For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_irq_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / 10) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System cpu - iowait",
   "type": "graph",
   "description": "The percentage of time the CPU spent waiting for IO operations to complete. For servers with more than 1 CPU core, this value can exceed 100%\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(hardware_system_cpu_io_wait_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / 10) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System cpu - nice",
   "type": "graph",
   "description": "The percentage of time the CPU spent occupied by all processes with a positive nice value. For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_nice_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / 10) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System cpu - kernel",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing operating system calls from all processes. For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_kernel_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / 10) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "System cpu - user",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing all user applications (not just MongoDB processes). For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_user_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / 10) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  { "title": "Normalized System Cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Normalized System cpu - steal",
   "type": "graph",
   "description": "The percentage of time the CPU had something runnable, but the hypervisor chose to run something else. It is scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_steal_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / (10 * hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"})) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "Normalized System cpu - guest",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing guest, which is included in user. It is scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_guest_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / (10 * hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"})) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "Normalized System cpu - softirq",
   "type": "graph",
   "description": "The percentage of time the CPU spent performing software interrupts. It is scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_soft_irq_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / (10 * hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"})) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "Normalized System cpu - irq",
   "type": "graph",
   "description": "The percentage of time the CPU spent performing hardware interrupts. It is scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_irq_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / (10 * hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"})) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "Normalized System cpu - iowait",
   "type": "graph",
   "description": "The percentage of time the CPU spent waiting for IO operations to complete. It is scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(hardware_system_cpu_io_wait_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / (10 * hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"})) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "Normalized System cpu - nice",
   "type": "graph",
   "description": "The percentage of time the CPU spent occupied by all processes with a positive nice value. It is scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_nice_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / (10 * hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"})) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "Normalized System cpu - kernel",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing operating system calls from all processes. It is scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_kernel_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / (10 * hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"})) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  {
   "title": "Normalized System cpu - user",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing all user applications (not just MongoDB processes). It is scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_cpu_user_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / (10 * hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"})) by (instance) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}}"
    }
   ]
  },
  { "title": "System Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "The average rate of physical bytes received per second by the eth0 network interface\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_network_eth0_bytes_in_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval])) by (instance) + sum(rate(hardware_system_network_lo_bytes_in_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval])) by (instance), \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "rx - {{hostname}}"
    },
    {
     "expr": "label_replace( -1 * sum(rate(hardware_system_network_eth0_bytes_out_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval])) by (instance) + sum(rate(hardware_system_network_lo_bytes_out_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval])) by (instance), \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "tx - {{hostname}}"
    }
   ]
  },
  { "title": "System Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "System Disk - Free",
   "type": "graph",
   "description": "The total bytes of free disk space on the disk partition used by MongoDB.\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(hardware_disk_metrics_disk_space_free_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance, disk_name) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}}, host - {{hostname}} "
    }
   ]
  },
  {
   "title": "System Disk Percent Free",
   "type": "graph",
   "description": "The percent of free disk space on the partition used by MongoDB.\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(hardware_disk_metrics_disk_space_free_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"} / (hardware_disk_metrics_disk_space_used_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"} + hardware_disk_metrics_disk_space_free_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) * 100) by (instance, disk_name) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}}, host - {{hostname}} "
    }
   ]
  },
  {
   "title": "System Disk - Used",
   "type": "graph",
   "description": "The total bytes of used disk space on the partition that runs MongoDB.\n",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(hardware_disk_metrics_disk_space_used_bytes{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance, disk_name) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}} host - {{hostname}} "
    }
   ]
  },
  {
   "title": "System Disk Write IOPS",
   "type": "graph",
   "description": "The write throughput of I/O operations per second for the disk partition used for MongoDB.\n",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "yaxes": [
    { "format": "/ sec" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_disk_metrics_write_count{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval])) by (instance, disk_name) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}} host - {{hostname}} "
    }
   ]
  },
  {
   "title": "System Disk Write Latency",
   "type": "graph",
   "description": "The write latency in milliseconds of the disk partition used by MongoDB.\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_disk_metrics_write_time_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / rate(hardware_disk_metrics_write_count{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval])) by (instance, disk_name), \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}} host - {{hostname}} "
    }
   ]
  },
  {
   "title": "System Disk Read Latency",
   "type": "graph",
   "description": "The Read latency in milliseconds of the disk partition used by MongoDB.\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_disk_metrics_read_time_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) / rate(hardware_disk_metrics_read_count{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval])) by (instance, disk_name), \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}} host - {{hostname}} "
    }
   ]
  },
  {
   "title": "System Disk Read IOPS",
   "type": "graph",
   "description": "The read throughput of I/O operations per second for the disk partition used for MongoDB.\n",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "yaxes": [
    { "format": "/ sec" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_disk_metrics_read_count{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval])) by (instance, disk_name) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}} host - {{hostname}} "
    }
   ]
  },
  {
   "title": "System Disk Util %",
   "type": "graph",
   "description": "The percentage of time during which requests are being issued to and serviced by the partition. This includes requests from any process, not just MongoDB processes.\n",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_disk_metrics_total_time_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) ) by (instance, disk_name) / 10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}} host - {{hostname}} "
    }
   ]
  },
  {
   "title": "System Disk Queue Depth",
   "type": "graph",
   "description": "The average length of queue of requests issued to the disk partition used by MongoDB.\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_disk_metrics_weighted_time_io_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) ) by (instance, DiskName), \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "disk - {{disk_name}} host - {{hostname}} "
    }
   ]
  },
  { "title": "Process CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Normalized Process cpu - user",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing this MongoDB process, scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace((sum(rate(hardware_process_cpu_user_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\", process_port=~\"$process_port\" } [$interval])) by (instance, process_port)  / on(instance) group_left  hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\" })/10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}} port - {{process_port}}"
    }
   ]
  },
  {
   "title": "Normalized Process cpu - children user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace((sum(rate(hardware_process_cpu_children_user_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\", process_port=~\"$process_port\" } [$interval])) by (instance, process_port)  / on(instance) group_left  hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\" })/10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}} port - {{process_port}}"
    }
   ]
  },
  {
   "title": "Normalized Process cpu - kernel",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing operating system calls for this MongoDB process, scaled to a range of 0-100% by dividing by the number of CPU cores.\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace((sum(rate(hardware_process_cpu_kernel_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\", process_port=~\"$process_port\" } [$interval])) by (instance, process_port)  / on(instance) group_left  hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\" })/10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}} port - {{process_port}}"
    }
   ]
  },
  {
   "title": "Normalized Process cpu - children kernel",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace((sum(rate(hardware_process_cpu_children_kernel_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\", process_port=~\"$process_port\" } [$interval])) by (instance, process_port)  / on(instance) group_left  hardware_platform_num_logical_cpus{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\" })/10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}} port - {{process_port}}"
    }
   ]
  },
  {
   "title": "Process cpu - user",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing this MongoDB process. For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(hardware_process_cpu_user_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\", process_port=~\"$process_port\" } [$interval])) by (instance, process_port)  / 10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}} port - {{process_port}}"
    }
   ]
  },
  {
   "title": "Process cpu - child user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(hardware_process_cpu_children_user_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\", process_port=~\"$process_port\" } [$interval])) by (instance, process_port)  / 10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}} port - {{process_port}}"
    }
   ]
  },
  {
   "title": "Process cpu - kernel",
   "type": "graph",
   "description": "The percentage of time the CPU spent servicing operating system calls for this MongoDB process. For servers with more than 1 CPU core, this value can exceed 100%.\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(hardware_process_cpu_kernel_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\", process_port=~\"$process_port\" } [$interval])) by (instance, process_port)  / 10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}} port - {{process_port}}"
    }
   ]
  },
  {
   "title": "Process cpu - children kernel",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(hardware_process_cpu_children_kernel_milliseconds{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\", process_port=~\"$process_port\" } [$interval])) by (instance, process_port)  / 10, \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "host - {{hostname}} port - {{process_port}}"
    }
   ]
  },
  { "title": "Misc.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "System VM Swap IO",
   "type": "graph",
   "description": "The total number of pages swapped in and out per second\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "yaxes": [
    { "format": "/ sec" }
   ],
   "targets": [
    {
     "expr": "label_replace( sum(rate(hardware_system_vm_page_swap_in{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) ) by (instance), \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "swap in for host - {{hostname}} "
    },
    {
     "expr": "label_replace( sum(rate(hardware_system_vm_page_swap_out{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}[$interval]) ) by (instance), \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "swap out for host - {{hostname}} "
    }
   ]
  }
 ]
}